### ISSUE TITLE
create 'contributing' page

### ISSUE THREAD

**Issue by ashleygould** [ucopacme/organizer#2]
document our workflow process for other users in a CONTRIBUTING.rst file in our project root

**Comment by ericodell** [comment]
@ashleygould  can you make contributing doc in a diff repo (a admin repo?) and then point to it from every other repo? this way we have one source of truth? can put link to contributing in readme.rst template. Also can we get this to the point where we could host all the stuff you have in your docs s3 so that we can pretend that github is the place to be? could be most useful if we get private github setup and chained to AD so that we can migrate all our disperate git repos to one place. Also could be good if your agile manifesto was in github with the project tools etc so we have a base to build on instead of using jira/box/sharepoint/email/xls

**Comment by ericodell** [comment]
fully merged
